### PR TITLE
Checkout screen

### PR DESCRIPTION
**Pull request by AngelicaGE**
Trello card: https://trello.com/c/qFlux5xs/4-checkout-screen

Changes include:
- checkout screen
- checkout module to list products when clicked on Eye icon
- APIs to bring store addresses and load cart info for checkout
- Some UI elements do not have functionality as they require backend implementation and are noted on the code with a "TODO" note

### CODE REVIEW

**Comment by AngelicaGE** [comment]
Send to home address
Screenshot 2024-11-02 at 3 42 30 p m

**Comment by AngelicaGE** [comment]
BOPIS
Screenshot 2024-11-02 at 3 42 21 p m

**Comment by AngelicaGE** [comment]
List cart items on EYE icon click
Screenshot 2024-11-02 at 3 42 37 p m

**Comment by ainhoamugica** [comment]
LGTM!

**Review by ainhoamugica — APPROVED** [review]
LGTM!

**Pull request merged**
