### PR TITLE
6-order-details-screen

### PR DESCRIPTION
**Pull request by AngelicaGE**
Trello ticket: https://trello.com/c/jbs3BRSs/6-order-details-screen

Changes include:
- dynamic page for order details and UI
- redux for order opened
- api to fetch opened order
- fix or paths to public folder
- clean npm dependencies
- create new order when checkout cart and redirect to order details
- create api to fill cart randomly

### CODE REVIEW

**Comment by AngelicaGE** [comment]
BOPIS ready for pickup
Screenshot 2024-11-06 at 5 18 50 p m

**Comment by AngelicaGE** [comment]
CANCELED order
Screenshot 2024-11-06 at 5 19 51 p m

**Comment by AngelicaGE** [comment]
CACELED ORDER
Screenshot 2024-11-09 at 12 00 13 a m

**Comment by AngelicaGE** [comment]
GET DELIVERED TO HOME ADDRESS
Screenshot 2024-11-09 at 12 05 48 a m

**Review by ainhoamugica — COMMENTED** [review]
In Grace's 1st order, there are no products yet it says completed not sure if this is an error.

Otherwise looks great!!!

**Comment by AngelicaGE** [comment]
> In Grace's 1st order, there are no products yet it says completed not sure if this is an error.
> 
> Otherwise looks great!!!

That is because I did not assign any products to that order. It is a backend issue, within this entry. I  will update it, thanks

**Pull request merged**
