### PR TITLE
2-chatbot

### PR DESCRIPTION
**Pull request by AngelicaGE**
Trello card: https://trello.com/c/tOE6Ue1F/2-chatbot?filter=label:H2%20-%20Leafy%20Personalization%20GenAI

This PR includes:
- floating btn to open chatbot modal
- Modal with 2 tabs
- chatbot tab with Chat wireframe (no functionality yet)
- architecture tab, currently in a "Comming soom status" since we do not have the diagram nor specific info we want to place there.

### CODE REVIEW

**Comment by AngelicaGE** [comment]
Tab 1 of modal
Screenshot 2024-10-30 at 3 42 39 p m

**Comment by AngelicaGE** [comment]
Tab 2 of modal
Screenshot 2024-10-30 at 3 42 52 p m

**Review by ainhoamugica — COMMENTED** [review]
Screenshot 2024-10-31 at 10 09 06

Looks great! Could you just make sure the input box is stuck at the bottom of the chatbox window? Ty!

**Comment by AngelicaGE** [comment]
@ainhoamugica Done! Thanks for that catch :D 
Screenshot 2024-10-31 at 3 22 43 p m

**Pull request merged**
