### PR TITLE
5-my-cart-screen

### PR DESCRIPTION
**Pull request by AngelicaGE**
Trello ticket https://trello.com/c/BjtTG8De/5-my-cart-screen

- Cart page UI done:
- It displays sckeleton when loading
- it shows list of products when cart had items in it
- it shows a message when cart is empty
- Move Login Modal to root layout so its included in all components not just Home.
- Redirect to /cart page on context menu click

Note: there is a button to "Fill cart randomly". This has no functionality yet since it will need backend implementation it will have behaviour when I get to the Trello card of backend for Cart Page.

### CODE REVIEW

**Comment by AngelicaGE** [comment]
Screenshot 2024-10-29 at 5 27 35 p m

**Comment by AngelicaGE** [comment]
Empty cart

Screenshot 2024-10-29 at 5 27 54 p m

**Comment by AngelicaGE** [comment]
Cart with items
Screenshot 2024-10-29 at 5 44 30 p m

**Review by ainhoamugica — APPROVED** [review]
Looks great!

**Pull request merged**
